name: Latest
on:
  push:
    branches:
    - master
jobs:
  release:
    name: Latest
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Runs goreleaser
      uses: docker://goreleaser/goreleaser
      id: goreleaser
      with:
        args: release --snapshot
