name: Release
on: create
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code
    uses: actions/checkout@v1

    - name: Install goreleaser
      run: go install github.com/goreleaser/goreleaser

    - name: GCR Setup
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.MY_GCLOUD_AUTH }}

    - name: GCR Auth
      uses: actions/gcloud/cli@master
      with:
        args: "auth configure-docker --quiet"

    - name: Runs goreleaser
      run: $(go env GOPATH)/bin/goreleaser release
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
